version: "3.8"

services:
  web:
    build: ./test-frontend
    ports:
      - "3013:80"
    restart: unless-stopped
  email-service:
    build: ./email-service
    ports:
      - "4000:9292"
    environment:
      - EZPROXY_EMAIL_RELAY=${EZPROXY_EMAIL_RELAY}
      - EZPROXY_EMAIL_SENDER=${EZPROXY_EMAIL_SENDER}
      - EZPROXY_EMAIL_TARGETS=${EZPROXY_EMAIL_TARGETS}
      - EZPROXY_CORS_ORIGINS=${EZPROXY_CORS_ORIGINS}

    restart: unless-stopped
  database:
    build: ./database-service
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-events}
      - POSTGRES_USER=${POSTGRES_USER:-ezproxy}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
  cleanup-service:
    build: ./cleanup-service
    environment:
      - CLEANUP_TIME=${CLEANUP_TIME:-02:00}
      - RETENTION_DAYS=${RETENTION_DAYS:-7}
      - PGHOST=database
      - PGDATABASE=${POSTGRES_DB:-events}
      - PGUSER=${POSTGRES_USER:-ezproxy}
      - PGPASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    depends_on:
      - database
